# Generated by Django 3.1.5 on 2021-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210125_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='', upload_to='videos')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='video',
        ),
    ]
